### ISSUE TITLE
Replacing config.json can invalidate HW_UID

### ISSUE THREAD

**Issue by sperok** [aulitech/Cato#159]
if config.json from a different Cato is copied to the device HW_UID will be incorrect.

**Comment by sperok** [comment]
check HW_UID when loading Config.json. Force hard reboot if incorrect

In boot.py check/correct HW_UID in config.json and UID- directory

**Comment by MiclFierro** [comment]
added in dev branch:
Setting uid in config has been moved from utils.py to boot.py to reduce necessary reboots and added a validation step to overwrite erroneous entries.
Additionally, in boot.py a folder with name "0x[uid]" is created and any other files/directories named in hex are removed

code review and release expected by eod
